### ISSUE TITLE
error: maskApi.c: No such file or directory

### ISSUE THREAD

**Issue by jhneo** [msracver/Relation-Networks-for-Object-Detection#5]
When I run     sh ./init.sh, an error comes
                  x86_64-linux-gnu-gcc: error: maskApi.c: No such file or directory
And I have installed  cython.  
It seems when run in lib/ dataset/pycocotools/
                 python setup_linux.py build_ext --inplace

**Comment by chengdazhi** [comment]
Hi, which python version are you using?

**Comment by miraclewkf** [comment]
It is not the problem of python. This problem is caused by the  missing of `maskApi.c` in `~/Relation-Networks-for-Object-Detection/lib/dataset/pycocotools/`, you can copy `maskApi.c` from `https://github.com/msracver/Deformable-ConvNets/tree/master/lib/dataset/pycocotools`.

@chengdazhi Maybe you can add `maskApi.c` file to this project.

**Comment by chengdazhi** [comment]
Many thanks to @miraclewkf  for pointing out the problem. We made a wrong modification to gitignore and as a result maskApi.c went missing. I have just pushed a new commit to fix this.
@jhneo you can pull the newest changes and try again. It should be fixed.
